// Generated by CoffeeScript 1.10.0
(function() {
  angular.module('judgebooklet', ['ngRoute', 'ngDraggable', 'pascalprecht.translate', 'judgebooklet.controller']).config([
    '$routeProvider', function($routeProvider) {
      return $routeProvider.when('/', {
        templateUrl: 'views/index.html',
        controller: 'IndexCtrl'
      }).otherwise({
        redirectTo: '/'
      });
    }
  ]).config([
    '$translateProvider', function($translateProvider) {
      var language;
      language = (function() {
        switch ((navigator.language || navigator.userLanguage).toLowerCase().substr(0, 2)) {
          case "fi":
            return "fi";
          case "fr":
            return "fr";
          case "de":
            return "de";
          case "es":
            return "es";
          case "it":
            return "it";
          default:
            return "en";
        }
      })();
      return $translateProvider.useStaticFilesLoader({
        prefix: 'translations/lang-',
        suffix: '.json'
      }).fallbackLanguage('en').preferredLanguage(language).useSanitizeValueStrategy('sanitizeParameters');
    }
  ]);

}).call(this);

//# sourceMappingURL=app.js.map
